# Generated by Django 5.2 on 2025-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist_app', '0004_ocrupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
